apiVersion: v1
kind: Pod
metadata:
  name: busy-box
  labels:
    dept: dept-busy-box

spec:
  restartPolicy: Never # Never
  terminationGracePeriodSeconds: 5 # Terminate Grace Period
  containers:
    - name: busy-box
      image: busybox
      command: [ "sleep" ] # Docker EntryPoint
      args: [ "3600" ]
      env:
        - name: "spring.application.name"
          value: "WSD-Team"