apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    dept: dev-team
    team: team-a
spec:
  restartPolicy: Always
  containers:
    - name: nginx
      image: nginx
      ports:
        - name: "nginx-gateway"
          containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  labels:
    dept: dev-team
    team: team-b
spec:
  containers:
    - name: nginx
      image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-3
  labels:
    dept: devops-team
    team: team-a
spec:
  containers:
    - name: nginx
      image: nginx